### ISSUE TITLE
Add support for bias flags

### ISSUE THREAD

**Issue by uSpike** [python-trio/trio-gpio#6]
https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/commit/include/gpiod.h?id=26d8d8f0b7bc0e300aaab05c75d5af1b0686af08 added the `GPIOD_LINE_REQUEST_FLAG_BIAS_DISABLE`, `GPIOD_LINE_REQUEST_FLAG_BIAS_PULL_UP`
and `GPIOD_LINE_REQUEST_FLAG_BIAS_PULL_DOWN` flags.

**Comment by smurfix** [comment]
Thanks, I'll look into that. Pull request welcome. ;-)

**Comment by uSpike** [comment]
PR submitted.  I'd be super happy if you could please create a new release with that change.  Cheers.
